services:
  webdav-nfs:
    image: nedix/webdav-nfs
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse:rwm
    environment:
      WEBDAV_ENDPOINT: ${WEBDAV_ENDPOINT}
      WEBDAV_PASSWORD: ${WEBDAV_PASSWORD}
      WEBDAV_USERNAME: ${WEBDAV_USERNAME}
    ports:
      - 127.0.0.1:${NFS_PORT:=2049}:2049

  example-container:
    image: busybox
    volumes:
      - webdav-nfs:/data
    depends_on:
      webdav-nfs:
        condition: service_healthy

volumes:
  webdav-nfs:
    driver_opts:
      type: 'nfs'
      o: 'vers=4,addr=127.0.0.1,port=${NFS_PORT:=2049},rw'
      device: ':/'
